function [fitresult, gof] = createFit(log_exposure, bias)
%CREATEFIT(LOG_EXPOSURE,BIAS)
%  Create a fit.
%
%  Data for 'bias_fit' fit:
%      X Input : log_exposure
%      Y Output: bias
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 18-Nov-2016 10:21:18


%% Fit: 'bias_fit'.
[xData, yData] = prepareCurveData( log_exposure, bias );

% Set up fittype and options.
ft = fittype( 'exp2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [898.407953425918 0.00066972548901598 -0.309797579756372 -0.721112436461564];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'bias_fit' );
h = plot( fitresult, xData, yData );
legend( h, 'bias vs. log_exposure', 'bias_fit', 'Location', 'NorthEast' );
% Label axes
xlabel log_exposure
ylabel bias
grid on


